---
title: "GPC-UNI Resto del mundo"
---

Entrenamiento de verano de programacion competitiva UNI Resto del mundo 2020

#### Entrenadores
- José Leonidas García Gonzales  
- Miguel Alessandro Mini Huambachano  
- Victor Racsó Galván Oyola  
- Sergio Sanchez Rojas  

## Semana 1

- [Introducción](./class-01.html)
- [Complejidades + STL](./class-02.html)

## Semana 2

- [Contest 1](./class-03.html)
- [Teoría de números](./class-04.html)

## Semana 3
- [Fuerza Bruta I](./class-05.html)
- [Fuerza Bruta II](./class-06.html)

## Semana 4
- [Contest 2](./class-07.html)
- [Recursión](./class-08.html)

## Semana 5
- [Backtracking I](./class-09.html)
- [Recapitulacion I](./class-10.html)

## Semana 6
- [Contest UNI-UTEC I](./class-11.html)
- [Repaso](./class-12.html)

## Semana 7
- [Backtracking II](./class-13.html)
- [Bitmask](./class-14.html)

## Semana 8
- [Introducción a Greedy](./class-15.html)
- [7 Greedy Problems](./class-16.html)

## Semana 9
- [Meet in the middle](./class-17.html)

## Semana 10
- [Dynamic Programming](./class-18.html)

## Semana 11
- [Introducción a la teoría de grafos](./class-19.html)

## Semana 12
- [Divide and Conquer](./class-20.html)

## Semana 13
- [Dynamic Programmic Classic Problems](./class-21.html)
- [Max Flow](./class-22.html)

## Training Camp Argentina 2020

- [Editorial Contest 1 - Inicial](./TCAC1-EditorialI.html)

- [Editorial Contest 1 - Avanzado](./TCAC1-EditorialA.html)

## Semana 14

- [Max Flow II](./class-23.html)

## Semana 15

- [Sparse Table](./class-24.html)

- [Binary Indexed Tree](./class-25.html)

## Semana 16

- [Introducción a Strings - I](./class-26.html)

- [Introducción a Strings - II](./class-27.html)
