---
title: "Plan semanal"
---

### Semana 1

- [Clase 1: Introduccion a la programación competitiva](./class-01.html) - Racso
  * ¿Qué es programación competitiva?
  * Principales competencias
  * Plataformas a usar
  * Conceptos iniciales: competencia, estructura de problemas, veredictos
    y estilos de competencias 

- [Clase 2: Complejidades + STL](./class-02.html) - Leonidas
  * Complejidad algorítmica: problema motivacional
  * Notación Big-O
  * Standard template Library (STL): introducción
  * Tipos de datos numéricos y operaciones aritméticas< 
  * string
  * vector
  * set
  * map

### Semana 2

- [Clase 3: Team contest 1](./class-03.html) - Miguel
  * Implementación
  * STL

- [Clase 4: Teoría de números](./class-04.html) - Miguel
  * Relaciones de congruencia
  * Aritmética modular
  * Máximo común divisor
  * Exponenciación rápida
  * Algoritmo de Euclides
  * Identidad de Bézout
  * Pequeño teorema de Fermat
  * Teorema de Euler
  * Teorema chino del resto
  * Hallando divisores
  * Hallando números primos
  * Criba de Eratóstenes

### Semana 3

- [Clase 5: Fuerza bruta 1](./class-05.html) - Leonidas
  * Paradigmas de problem solving
  * Tripletas pitagóricas
  * Fijando variables
  * Simulación con fuerza bruta
  * Weak constraints
  * Análisis por casos
  * Extra: Prefix sums

- [Clase 6: Fuerza bruta 2](./class-06.html) - Leonidas
  * Two pointers
  * Contribution technique
  * Búsqueda en todas las permutaciones

### Semana 4

- [Clase 7: Team contest 2](./class-07.html) - Leonidas
  * Teoría de números
  * Fuerza bruta 1
  * Fuerza bruta 2

- [Clase 8: Recursión](./class-08.html) - Leonidas
  * Nociones básicas
  * Las torres de Hanoi
  * Ejercicios
  * Aritmética y recursión
  * Fractales
  
### Semana 5

- [Clase 9: Backtracking 1](./class-09.html) - Leonidas
  * Conjunto potencia
  * El problema de la mochila 0-1
  * Permutaciones
  * Sudoku
  * El problema de las N-reinas

- [Clase 10: Recapitulación I](./class-10.html) - Racso
  * Calentamiento
  * Fuerza bruta
  * Backtracking

### Semana 6

- [Clase 11: Contest UNI-UTEC-UPC I](./class-11.html) - Leonidas Miguel Racso

- [Clase 12: Repaso](./class-12.html) - Miguel
  * Backtracking

### Semana 7

- [Clase 13: Backtracking II](./class-13.html) - Miguel
  * Optimización y conteo con backtracking
    + El problema de la mochila
    + Parenthesis Balance
    + Sequence Problem
  * Trabajando con conjuntos de forma más óptima

- Clase 14: bitmask + complete search - Miguel
  * minimum independent set
  * recreando divisores
  * generando numeros con un patron.

### Semana 8

- [Clase 15: Introducción a Greedy](./class-15.html) - Racso
  * ¿Qué es la programación Greedy?
  * ¿Cómo estar seguro de que el greedy funciona?

- [Clase 16: 7 Greedy Problems](./class-16.html) - Miguel
  * Problemas

### Semana 9

- [Clase 17: Meet in the middle](./class-17.html) - Miguel
  * ¿Qué es meet in the middle?
    - Un algoritmo de fuerza bruta más inteligente
    - Código
    - Nueva Complejidad
  * Baby Step Giant Step
    - Código asumiendo n: primo $O(\sqrt n \log n)$
  * Problemas

- Clase 18: Contest UNI-UTEC-UPC II - Leonidas Miguel Racso (Sergio?)
  * Contest
  * Compartir
